# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id_facultet', models.AutoField(primary_key=True, serialize=False)),
                ('name_faculty', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': '\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442',
                'verbose_name_plural': '\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b',
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id_kafedra', models.AutoField(primary_key=True, serialize=False)),
                ('name_kafedra', models.CharField(max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0444\u0435\u0434\u0440\u044b')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0444\u0435\u0434\u0440\u0430',
                'verbose_name_plural': '\u041a\u0430\u0444\u0435\u0434\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('answer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Answers')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id_speciality', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15, verbose_name='\u041a\u043e\u0434')),
                ('name_speciality', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Faculty', verbose_name='\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='Student_subject',
            fields=[
                ('id_rel_st_sub', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442-\u043f\u0440\u0435\u0434\u043c\u0435\u0442',
                'verbose_name_plural': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442\u044b-\u043f\u0440\u0435\u0434\u043c\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('otchestvo', models.CharField(max_length=50, null=True)),
                ('login', models.CharField(max_length=50)),
                ('pasword', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Group')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442',
                'verbose_name_plural': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name_subject', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u044b')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Kafedra', verbose_name='\u041a\u0430\u0444\u0435\u0434\u0440\u0430')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Speciality', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u0414\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u0430',
                'verbose_name_plural': '\u0414\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('otchestvo', models.CharField(max_length=50, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('login', models.CharField(max_length=15, verbose_name='\u041b\u043e\u0433\u0438\u043d')),
                ('password', models.CharField(max_length=150, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Kafedra')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Testirovanie',
            fields=[
                ('id_testirovania', models.AutoField(primary_key=True, serialize=False)),
                ('stud_answer', models.CharField(max_length=50, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('id_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Questions', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('stud_subj_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Student_subject', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0422\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(default='', verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('date_finish', models.DateTimeField(default='', verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('test_time', models.IntegerField(default='', verbose_name='\u0412\u0440\u0435\u043c\u044f \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('count_questions', models.SmallIntegerField(default='', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Subjects', verbose_name='\u0414\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u0430')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Teachers', verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0441\u0442',
                'verbose_name_plural': '\u0422\u0435\u0441\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='testirovanie',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Tests', verbose_name='\u0422\u0435\u0441\u0442\u0438\u0440\u0443\u0435\u043c\u0430\u044f \u0434\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Teachers', verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='student',
            field=models.ManyToManyField(to='BD.Students'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='subject',
            field=models.ManyToManyField(to='BD.Subjects'),
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Speciality'),
        ),
    ]
