# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id_facultet', models.AutoField(primary_key=True, serialize=False)),
                ('name_faculty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id_kafedra', models.AutoField(primary_key=True, serialize=False)),
                ('name_kafedra', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
                ('answer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Answers')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id_speciality', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15)),
                ('name_speciality', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student_subject',
            fields=[
                ('id_rel_st_sub', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('otchestvo', models.CharField(max_length=50, null=True)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name_subject', models.CharField(max_length=20)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Kafedra')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('otchestvo', models.CharField(max_length=50, null=True)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Testirovanie',
            fields=[
                ('id_testirovania', models.AutoField(primary_key=True, serialize=False)),
                ('stud_answer', models.CharField(max_length=50)),
                ('id_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Questions')),
                ('stud_subj_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Student_subject')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Teachers')),
            ],
        ),
        migrations.AddField(
            model_name='testirovanie',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Tests'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Teachers'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='student',
            field=models.ManyToManyField(to='BD.Students'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='subject',
            field=models.ManyToManyField(to='BD.Subjects'),
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Speciality'),
        ),
    ]
